cmake_minimum_required(VERSION 3.25)

if (NOT DEFINED REPOSITORY_ROOT)
    get_filename_component(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

function(require_file relative_path)
    if (NOT EXISTS "${REPOSITORY_ROOT}/${relative_path}")
        message(FATAL_ERROR "Public repository file is missing: ${relative_path}")
    endif()
endfunction()

function(require_text relative_path expected_text)
    require_file("${relative_path}")
    file(READ "${REPOSITORY_ROOT}/${relative_path}" contents)
    string(FIND "${contents}" "${expected_text}" match_position)
    if (match_position EQUAL -1)
        message(FATAL_ERROR
            "${relative_path} does not contain required public-release text: ${expected_text}")
    endif()
endfunction()

function(require_absent relative_path)
    if (EXISTS "${REPOSITORY_ROOT}/${relative_path}")
        message(FATAL_ERROR "Private or internal path remains in repository: ${relative_path}")
    endif()
endfunction()

require_text("CMakeLists.txt" "COMPANY_NAME \"Nijat Burjiyev\"")
require_text("CMakeLists.txt" "BUNDLE_ID com.nijatburjiyev.spectralrelief")
require_text("CMakeLists.txt" "PRODUCT_NAME \"Spectral Relief\"")
require_text("CMakeLists.txt" "PLUGIN_MANUFACTURER_CODE Nbsp")
require_text("CMakeLists.txt" "PLUGIN_CODE SpRl")
require_text("LICENSE" "GNU AFFERO GENERAL PUBLIC LICENSE")
require_text("LICENSE" "Version 3, 19 November 2007")
require_text("README.md" "Nijat Burjiyev")
require_text("README.md" "free, open-source VST3 audio spectrogram plugin")
require_text("README.md" "docs/assets/spectral-relief-demo.gif")
require_file("docs/assets/spectral-relief-demo.gif")
require_text("README.md" "AGPL-3.0-only")
require_text("README.md" "googlecreativelab/chrome-music-lab")
require_text("docs/testing/ableton-smoke-test.md" "VST3 → Nijat Burjiyev")
require_text("THIRD_PARTY_NOTICES.md" "Chrome Music Lab")
require_text("THIRD_PARTY_NOTICES.md" "Apache License 2.0")
require_text("CONTRIBUTING.md" "Developer Certificate of Origin")
require_file("SECURITY.md")
require_file(".github/workflows/ci.yml")
require_text(".github/workflows/ci.yml" "runs-on: macos-15")

require_absent("docs/superpowers")
require_absent("docs/*.pdf")
require_absent("tmp")

message(STATUS "Public release audit passed")
